### PR TITLE
Update to CircleCI 2.0

### PR DESCRIPTION
**Pull request by kulinacs**
Upgrading to CircleCI 2.0 will allow usage of versions of Docker newer than 1.9.0, allowing features like Healthcheck to be added. The updated build process can be seen here:

https://circleci.com/gh/kulinacs/grafana-docker/7
https://circleci.com/gh/kulinacs/grafana-docker/8

Note the failure on master is due to the fact I do not have push permissions to the Docker Hub repository, not an error with the script.

Additionally, the shebang line was modified to `/bin/sh` to allow for building on systems that do not include bash. This is useful in CircleCI's new containerized build process, allowing for quicker builds overall (00:58 vs 04:42 in my case)

### CODE REVIEW

**Comment by Dieterbe** [comment]
> (00:58 vs 04:42 in my case)

do you know where these improvements come from? i suspect the majority are from the new 2.0 infrastructure itself, switching bash for a lightweight posix shell probably results in some gains but i would expect those to be less significant.

**Comment by kulinacs** [comment]
The speed increase will be largely from moving from the machine exector in CircleCI 1.0 to the Docker executor in CircleCI 2.0, removing the need to provision a VM for each run.

**Comment by jstoja** [comment]
@bergquist I think this would be very nice for future PRs (and the sake of using the latest CI version)

**Comment by kulinacs** [comment]
Any more progress on this? CircleCI 1.0 is being sunset on August 31st, 2018.

**Comment by xlson** [comment]
@kulinacs: Looks great, thanks for updating the build. We just updated the the main Grafana build to 2.0 as well so this should give us an even shorter build time right through the whole build pipeline.

**Pull request merged**
