### PR TITLE
Fix for #119, remove failure on error

### PR DESCRIPTION
**Pull request by briantopping**

### CODE REVIEW

**Comment by jstoja** [comment]
This seems to be a reasonable change. +1 for it.

**Comment by xlson** [comment]
Can you explain what your usecase is for this change? I'd rather have the container fail fast as that makes it more clear what the problem is than failing in runtime. If there are mistake in the run script that makes it fail when it shouldn't those should be corrected instead of removing the fail fast option.

**Comment by briantopping** [comment]
My bad, I didn't see that the description was empty. If I've done this before in life, I don't remember it. And I have filed a lot of issues. 

That said, three months to get to this point?

I'll update the original description, if I still can.

**Comment by xlson** [comment]
Thank you.

I'm sorry it took us this long to respond, three months is definitely not what we're aiming for in terms of initial response. We're actively working on improving our routines for handling PR's and issues.

**Comment by xlson** [comment]
@briantopping No need to update the description, you had created an issue as well (#119). I've responded to it too. Once more, sorry for taking so long to get back to you.

**Comment by briantopping** [comment]
Ah indeed, I just noticed same. I must have accidentally submitted twice. Thanks @xlson! I'll comment there.

**Pull request closed without merging**
