### PR TITLE
Support for env variables ending with _FILE

### PR DESCRIPTION
**Pull request by efrecon**
This slight modification to the main run script will recognise environment variables starting with `GF_` and ending with `_FILE`. Whenever such variables exist, the content of the file that they point at will be read and used to set the same environment variable, but without the `_FILE` ending. This is handy when using Docker secrets and solves #149 . The use of the ending `_FILE` is inspired by other official images, such as [postgres](https://hub.docker.com/_/postgres/) for example.

### CODE REVIEW

**Comment by efrecon** [comment]
Any comment/news about this PR?

**Comment by xlson** [comment]
@DanCech any thoughts regarding this PR? Seems like a good addition to me.

**Comment by DanCech** [comment]
The concept is an interesting one, the code can be simplified to:
```
for VAR_NAME in $(env | grep '^GF_[^=]\+_FILE=.\+' | sed -r "s/([^=]*)_FILE=.*/\1/g"); do
  VAR_NAME_FILE="$VAR_NAME"_FILE
  if [ "${!VAR_NAME}" ]; then
    echo >&2 "ERROR: Both $VAR_NAME and $VAR_NAME_FILE are set (but are exclusive)"
    exit 1
  fi
  echo "Getting secret $VAR_NAME from ${!VAR_NAME_FILE}"
  export "$VAR_NAME"="$(< "${!VAR_NAME_FILE}")"
  unset "$VAR_NAME_FILE"
done
```

**Comment by efrecon** [comment]
Fine by me, do you want to take in the PR and make the change manually afterwards?

**Comment by DanCech** [comment]
I committed the tweaked version, @efrecon can you confirm that the updated code works for you?

**Comment by efrecon** [comment]
Confirmed that your changes worked @DanCech , good to go @xlson .

**Comment by xlson** [comment]
Thanks guys! Merging this now!

**Comment by xlson** [comment]
@efrecon it looks like we'll be doing a beta release very soon so I'll write up the docs myself. Thanks anyway.

**Comment by efrecon** [comment]
Feel free to pick anything (or nothing) from [here](https://efrecon.github.io/docker-secrets-with-grafana/) if necessary.

**Comment by xlson** [comment]
@efrecon Thanks for sharing your post!

**Pull request merged**
